apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: jenkins
  namespace: devops-tools
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-server
  type: LoadBalancer
status:
  loadBalancer: {}